### ISSUE TITLE
[no-conditional-statement] option to allow switch statements

### ISSUE THREAD

**Issue by jacobwgillespie** [jonaskello/eslint-plugin-functional#100]
Would it be possible to add an option to `no-conditional-statement` that allowed switch statements, forbidding only if statements? I would like to use this with [`@typescript-eslint/switch-exhaustiveness-check`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md), which allows for type-aware exhaustiveness checking without the default branch:

```typescript
type X = 'a' | 'b'

declare const x: X

// No explicit default case required here, 
// it's checked for exhaustiveness by the linter:
switch (x) {
  case 'a': return 1
  case 'b': return 2
}
```

**Comment by RebeccaStevens** [comment]
Exhaustiveness type checks are now allowed.
