### ISSUE TITLE
Definition for rule was not found

### ISSUE THREAD

**Issue by johndatserakis** [jonaskello/eslint-plugin-functional#105]
Hi there, sorry to bother with this, but I'm running into an issue, only when building, in [this](https://github.com/johndatserakis/koa-react-notes-web.) public repo. 

The issue is with disabling an eslint rule concerning a line. For now, I can just use `// eslint-disable-next-line`, but I don't like that because I lose the information of what exactly I'm trying to disable on that line. The file in question is [here](https://github.com/johndatserakis/koa-react-notes-web/blob/master/src/common/axios.ts) on line 22. (For now I just have an additional comment above the line, noting what I am disabling, please don't mind that.)

The error I'm getting when building is:

```
Definition for rule 'functional/immutable-data' was not found  functional/immutable-data
```

There is a place in my code where I have to mutate some data. Of course, not an issue, so I added

```
// eslint-disable-next-line functional/immutable-data
```

Above the line I needed to skip. That worked fine, the error went away in my vscode "problems" pane just like I expected it to.

The thing is, when building, the error showed up and stopped the build. Strange...

The `.eslintrc.js` is [here](https://github.com/johndatserakis/koa-react-notes-web/blob/master/.eslintrc.js).
The `tsconfig.json` is [here](https://github.com/johndatserakis/koa-react-notes-web/blob/master/tsconfig.json).

If anyone has any ideas or pointers I'd really appreciate it. Thank you.

**Comment by krailler** [comment]
Same here

**Comment by DylanRJohnston** [comment]
Here's a minimal example the exhibits the problem. https://github.com/DylanRJohnston/async-workshop/tree/f2e1d106dfaf06f8fbbeb26aaef69e654bb0d397

**Comment by DylanRJohnston** [comment]
I'm missing the

```
plugins:
  - functional
```

🤦

**Comment by RebeccaStevens** [comment]
@johndatserakis Is this still being an issue for you?

**Comment by RebeccaStevens** [comment]
Closing due to no response.
