### ISSUE TITLE
[prefer-type-literal] Default whitelist

### ISSUE THREAD

**Issue by zEh-** [jonaskello/eslint-plugin-functional#156]
### I think of this as enough of a regular case to maybe be worth to be handled.

```typescript
declare global {
  // eslint-disable-next-line functional/prefer-type-literal
  interface Window {
    // ...
  }
}
```

**Just another thanks for this project!**

**Comment by RebeccaStevens** [comment]
Maybe it would be best for the rule to just ignore everything inside a module declaration (`TSModuleDeclaration` nodes). @jonaskello See anything wrong with this idea?

**Comment by jonaskello** [comment]
I think that could work. I also noticed there is a rule in `@typescript-eslint` that seems very similar: [@typescript-eslint/consistent-type-definitions](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-definitions.md). Would be interesting to see how that rule handles this case. Also thinking if we don't have anything extra to offer in our rule we might consider removing it and recommend that rule instead.

**Comment by RebeccaStevens** [comment]
That rule does look very similar. In that case I think that yes, we should deprecate this rule in favor of that one. Our rule doesn't do anything special.

I don't know if that rule handles the issue raised here or not but if it doesn't, an issue can be raised there for it.

**Comment by RebeccaStevens** [comment]
Made a new issue for deprecating the rule - #170
