### ISSUE TITLE
Fails to parse some usages of String constructor

### ISSUE THREAD

**Issue by samhh** [jonaskello/eslint-plugin-functional#194]
```
TypeError: Cannot read property 'type' of undefined
```

Minimal repro: `const f = (x: number) => String(x)`

It seems you need to specifically pass an argument into the constructor in return position for this to occur.

This only happens on 3.2.1, not 3.1.0.

**Comment by RebeccaStevens** [comment]
@samhh I haven't been able to reproduce this issue.
Does this issue occur with a specific rule?

Would you be able to provide a larger example?

**Comment by RebeccaStevens** [comment]
Found the issue. It's with the prefer-tacit rule.
