### ISSUE TITLE
Merge rules: no-throw, no-try (possibly also no-reject)

### ISSUE THREAD

**Issue by RebeccaStevens** [jonaskello/eslint-plugin-functional#20]
See #11

**Comment by RebeccaStevens** [comment]
@jonaskello I'm not sure about merging these rules as they are designed to stop different things.

- `no-throw` is designed to prevent creating exceptions.
- `no-try` is designed to prevent handling exceptions (which often can't be avoided when it comes to 
 using non-functional 3rd-party libraries)
- `no-reject` is designed to prevent rejecting promises, making them act as a single type (rather than acting as a union of two types) [I consider this to be an anti-pattern but it's available for those that want it] (note: this rule must be used with `no-throw`)

If anything, I kind of feel like the `no-try` rule could be split into two rule; `no-catch` and `no-finally` (or maybe those should just be options).

**Comment by jonaskello** [comment]
I think we can keep them the same as in tslint-immutable, that will also make it easier to migrate.
