### ISSUE TITLE
Can this plugin be used without TypeScript?

### ISSUE THREAD

**Issue by yosevukilonzo** [jonaskello/eslint-plugin-functional#49]
Hello, it says in the readme that "Most rules can be used both for JavaScript and TypeScript". I assumed rules like `no-let` should work fine,  but I get a `Cannot find module 'typescript'` error. Please advise!

**Comment by RebeccaStevens** [comment]
Which version of this plugin are you using? This plugin should be usable without TypeScript from version 0.2.1 onwards.

I haven't personally checked yet to see if it is in fact working as intended. If your using the latest version and receiving that error, let me know and I'll look into the issue.

**Comment by RebeccaStevens** [comment]
I just tested this with v0.4 and I got that same error. I tried again with the master branch and didn't get any issues. I'm about to make a new release. Could you try with that and see If you have any issues?

**Comment by yosevukilonzo** [comment]
Hey, thanks for checking! I installed 0.5 and till getting `Error: Failed to load plugin 'functional' declared in '.eslintrc.js': Cannot find module 'typescript'` unfortunately. It works fine if I install typescript.

**Comment by RebeccaStevens** [comment]
Looks like this is an upstream issue with [@typescript-eslint/typescript-estree](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/README.md).
[I've created an issue for this](typescript-eslint/typescript-eslint#770).

As a work around for now, I'd recommend installing typescript as a devDependency.

```sh
npm install typescript --save-dev
```

**Comment by RebeccaStevens** [comment]
@yosevukilonzo, I've managed to modify the build process so that `@typescript-eslint` is no longer a dependency. In doing so, `typescript` will no longer be a peer dependency.

From the next release, things should now just work for vanilla JS out of the box.
