### ISSUE TITLE
Can immutability truly be enforced with ESLint or does it ultimately depend on developer discipline?

### ISSUE THREAD

**Issue by yosevukilonzo** [jonaskello/eslint-plugin-functional#61]
Hey, I have a question regarding this part of the README:

> Then TypeScript 2.0 came along and introduced readonly options for properties, indexers and arrays. TypeScript 3.0 has continued to add support immutability enforcing syntax. This enables us to use regular object and arrays and have the immutability enforced at compile time instead of run-time. Now the only drawback is that there is nothing enforcing the use of readonly in TypeScript.

>**This can be solved by using linting rules.** So one aim of this project is to leverage the type system in TypeScript to enforce immutability at compile-time while still using regular objects and arrays. Additionally, this project will also aim to support disabling mutability for vanilla JavaScript where possible.

Is there anything other than developer discipline that can prevent developers from using "Disabling Rules with Inline Comments"? Could you perhaps disallow use of `eslint-disable`?

**Comment by RebeccaStevens** [comment]
Developer discipline is needed, however use of ESLint directive-comments can be marked as linting errors with [eslint-plugin-eslint-comments](https://mysticatea.github.io/eslint-plugin-eslint-comments/).

But the developer could always just disable eslint all together and go about mutating anything they want.

**Comment by yosevukilonzo** [comment]
Thanks! I wasn't aware of that plugin.
