### ISSUE TITLE
Disallow type "never"

### ISSUE THREAD

**Issue by zEh-** [jonaskello/eslint-plugin-functional#67]
It's not possible to use a regular endless loop or throw an exception, but it might be a good idea to explicitly disallow type "never".
But that would mean, if you you disable "functional/no-throw-statement" in a situation, you would have to disable a potential "no-never" as well.

**Comment by RebeccaStevens** [comment]
Could you give a code example of where disabling type "never" would be wanted?

Type "never" can be quite useful in some situation, for example checking that a switch statement is exhaustive:

```ts
// somefile.ts

/* eslint-disable-next-line */
function assertNever(_value: never): void { }

type Options = 1 | 2 | 3;

const foo = 1 as Options;

switch (foo) {
  case 1:
  case 2:
  case 3:
    // ...
    break;
  default:
    assertNever(foo);
}
```

```jsonc
// .eslintrc

{
  // ...
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:functional/recommended"
  ],
  "rules": {
    "functional/no-conditional-statement": "off",
    "functional/no-expression-statement": [
      "error",
      {
        "ignorePattern": "assertNever\\(.*\\)"
      }
    ]
  }
}
```

Here, if a new option is added to the "Options" type, the "assertNever" call will error as "foo" is no longer of type "never".

**Comment by zEh-** [comment]
Just as I prefer undefined over null and disallow any, I never need "never". Your case is totally valid, it's just not a pattern I use - so feel free to dismiss it.

**Comment by RebeccaStevens** [comment]
I'll mark this as out of scope of this project.
If more information about how this relates to functional programming is given I'll consider reopening this issue.
